included:
  - Sources

excluded:
  - Tests
  - .build

disabled_rules:
  - trailing_comma
  - todo
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing
