included:
  - Sources

excluded:
  - Tests
  - .build

disabled_rules:
  - trailing_comma
  - todo
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - function_name_whitespace
  - implicit_optional_initialization
  - opening_brace
  - syntactic_sugar
  - trailing_whitespace
  - unused_closure_parameter
  - control_statement
